---
apiVersion: v1
kind: Namespace
metadata:
  name: sampathns
---
apiVersion: v1
kind: Pod
metadata:
  name: sampathpod
  namespace: sampathns
  labels:
    app: sampathapp
spec:
  containers:
    - name: sampathwebcontainer
      image: nginx
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sampathsvc
  namespace: sampathns
spec:
  selector:
    app: sampathapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
